In [9]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os
%matplotlib inline

from scipy.stats import ttest_1samp, ttest_ind, mannwhitneyu, levene, shapiro
from statsmodels.stats.power import ttest_power

In [48]:
## Set the working directory and import data
df = pd.read_csv("data.csv")
df.head()

   SALESPERSON  Old Scheme (in thousands)  New Scheme (in thousands)
0            1                         57                         62
1            2                        103                        122
2            3                         59                         54
3            4                         75                         82
4            5                         84                         84

In [49]:
df.describe()

       SALESPERSON  Old Scheme (in thousands)  New Scheme (in thousands)
count    30.000000                  30.000000                  30.000000
mean     15.500000                  68.033333                  72.033333
std       8.803408                  20.455980                  24.062395
min       1.000000                  28.000000                  32.000000
25%       8.250000                  54.000000                  55.000000
50%      15.500000                  67.000000                  74.000000
75%      22.750000                  81.500000                  85.750000
max      30.000000                 110.000000                 122.000000

In [51]:
#Question2: Answer

old_mean=df['Old Scheme (in thousands)'].mean()
new_mean=df['New Scheme (in thousands)'].mean()
# old scheme mean
print (old_mean)
# New scheme mean
new_mean

#The data is dependent data. Since the different test is performed on the same set of population
# Old and New Scheme has two different means, which is indicatiing the variance in the distribution
#two groups doesnt have the same mean at the 5% significance level
#The null hypothesis is U1=u2
#Alternative hypothesis u1!=u2

#it shows that new scheme is significantly raised outputs

68.03333333333333

72.03333333333333

In [38]:
group1 = df.loc[:,'Old Scheme (in thousands)']
print (group1)
group2 = df.loc[:,'New Scheme (in thousands)']
group2

0      57
1     103
2      59
3      75
4      84
5      73
6      35
7     110
8      44
9      82
10     67
11     64
12     78
13     53
14     41
15     39
16     80
17     87
18     73
19     65
20     28
21     62
22     49
23     84
24     63
25     77
26     67
27    101
28     91
29     50
Name: Old Scheme (in thousands), dtype: int64

0      62
1     122
2      54
3      82
4      84
5      86
6      32
7     104
8      38
9     107
10     84
11     85
12     99
13     39
14     34
15     58
16     73
17     53
18     66
19     78
20     41
21     71
22     38
23     95
24     81
25     58
26     75
27     94
28    100
29     68
Name: New Scheme (in thousands), dtype: int64

In [39]:
t_statistic, p_value = ttest_ind(group1, group2)
print(t_statistic, p_value)

-0.6937067608923764 0.49063515686248105

In [40]:
print ("two-sample t-test p-value=", p_value)
#Question 3:
 #P value= 0.49, which is 49% of the group.
# P value says that there could be 49% of rejection of Null hypothesis.

two-sample t-test p-value= 0.49063515686248105

In [41]:
u, p_value = mannwhitneyu(group1, group2)
print ("two-sample wilcoxon-test p-value=", p_value)

two-sample wilcoxon-test p-value= 0.24815395764270332

In [50]:
levene(group1,group2)

LeveneResult(statistic=1.063061539437244, pvalue=0.30679836081811235)

In [ ]:
#question 4

# Calculating Power of Test
# Compute the difference in Means between 2 sample means and divide by pooled Standard Deviation 
# number of Observations/tuples

#1) dont know how to increase the avg. output
#2)know to take the power of the test
#3)type 1 error is rejection of null hypothesis when it is true